### ISSUE TITLE
Using E-Book Viewer to open the books

### ISSUE THREAD

**Issue by zoenglinghou** [mpco/AlfredWorkflow-Calibre-Search#1]
It would be great if there is an option to open the e-book with the viewer app. The app is located at:

`/Applications/calibre.app/Contents/ebook-viewer.app`

It seems to me replacing the "Open File" action with a command `open -a /Applications/calibre.app/Contents/ebook-viewer.app {query}` could do the trick.

Thank you!

**Comment by mpco** [comment]
https://github.com/mpco/AlfredWorkflow-Calibre-Search/releases/tag/3.2
