### ISSUE TITLE
can  you please provide a .alfredworkflow, or instruction on how to install it

### ISSUE THREAD

**Issue by souhaiebtar** [mpco/AlfredWorkflow-Calibre-Search#3]

**Comment by a-rock-lobster** [comment]
There is an alfredworkflow file available for version 3.0

**Comment by mpco** [comment]
Sorry, I forgot to post the last version of the file. Now, it has been updated and released. 

https://github.com/mpco/AlfredWorkflow-Calibre-Search/releases

**Comment by a-rock-lobster** [comment]
Superb, thanks alot for publishing
